name: Build Add-on

permissions:
  pull-requests: write

on:
  workflow_call:

jobs:
  scons:
    if: "!contains(github.event.pull_request.labels.*.name, 'notForAddon')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name: Install dependencies
        run: pip install scons markdown
        
      - name: update packages
        run: sudo apt-get update
        
      - name: install gettext
        run: sudo apt-get install gettext

      - name: get commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: build with hash of commit
        run: scons version=$COMMIT_HASH 2> build_error.log        
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scanvox-${{ env.COMMIT_HASH }}
          path: ./*.nvda-addon
          if-no-files-found: error
          
      - name: comment on pull request if build fails
        uses: actions/github-script@v7
        if: failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            let body;
            
            if (fs.existsSync('build_error.log') && fs.statSync('build_error.log').size > 2) {
              const errorMessage = fs.readFileSync('build_error.log', 'utf8');
              body = `Add-on build failed with error:\n ${errorMessage}`;
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });