name: release
on: 
  workflow_call:
    inputs:
      nameTag:
        required: true
        type: string

jobs:
  scons: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install scons
        run: pip install scons
      - name: install markdown
        run: pip install markdown
      - name: Update packages
        run: sudo apt-get update
      - name: Install gettext
        run: sudo apt-get install gettext
      - name: Generating Addon
        run: scons
      - name: generating pot file
        run: scons pot
      - name: Upload the nvda add-on 
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.USER_SFTP }}
          server: ${{ secrets.HOST_SFTP }}
          port: ${{ secrets.PORT_SFTP }}
          local_path: './*.nvda-addon'
          remote_path: ${{ secrets.REMETE_SFTP }}
          sftp_only: true
          password: ${{ secrets.MDP_SFTP }}
      #- name: add file in release
        k#uses: softprops/action-gh-release@v2
        #env:
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #with:
          #tag_name: ${{ inputs.nameTag }}
          #files: |
            #*.nvda-addon
            #*.pot
          #body_path: changelog.md